version: '3.7'

services:
  scheduler:
    restart: "no"
    image: pigeosolutions/hyfaa-scheduler:4.0
    build: ./hyfaa-scheduler
    volumes:
      - ./hyfaa-scheduler/work_configurations/operational_niger_gsmap:/work
    networks:
      - net
networks:
  net:
