version: '3.7'

secrets:
  hydroweb_user:
    file: ./secrets/hydroweb_user.txt
  hydroweb_password:
    file: ./secrets/hydroweb_password.txt

services:
  scheduler:
    restart: "no"
    image: pigeosolutions/hyfaa-scheduler:4.2
    user: $USER_ID:$GROUP_ID
    build: ./hyfaa-scheduler
    secrets:
      - hydroweb_user
      - hydroweb_password
    environment:
      - HYDROWEB_USER_FILE=/run/secrets/hydroweb_user
      - HYDROWEB_PASSWORD_FILE=/run/secrets/hydroweb_password
    volumes:
      - ./hyfaa-scheduler/work_configurations/operational_niger_gsmap:/work
    networks:
      - net

  site:
    labels:
      # HTTP -> HTTPS redirect
      - "traefik.http.middlewares.site.redirectscheme.scheme=https"
      - "traefik.http.middlewares.site.redirectscheme.permanent=false"
      - "traefik.http.routers.site.middlewares=site@docker"

  frontend:
    labels:
      # HTTP -> HTTPS redirect
      - "traefik.http.middlewares.frontend.redirectscheme.scheme=https"
      - "traefik.http.middlewares.frontend.redirectscheme.permanent=false"
      - "traefik.http.routers.frontend.middlewares=frontend@docker"

  frontend-assim:
    labels:
      # HTTP -> HTTPS redirect
      - "traefik.http.middlewares.frontend-assim.redirectscheme.scheme=https"
      - "traefik.http.middlewares.frontend-assim.redirectscheme.permanent=false"
      - "traefik.http.routers.frontend-assim.middlewares=frontend-assim@docker"

  backend:
    labels:
      # HTTP -> HTTPS redirect
      - "traefik.http.middlewares.backend.redirectscheme.scheme=https"
      - "traefik.http.middlewares.backend.redirectscheme.permanent=false"
      - "traefik.http.routers.backend.middlewares=backend@docker"

  pg-tileserv:
    labels:
      # HTTP -> HTTPS redirect
      - "traefik.http.middlewares.pg-tileserv.redirectscheme.scheme=https"
      - "traefik.http.middlewares.pg-tileserv.redirectscheme.permanent=false"
      - "traefik.http.routers.pg-tileserv.middlewares=pg-tileserv@docker"

networks:
  net:
