version: '3.7'

services:
#  traefik:
#    volumes:
#      - ./config/traefik-dev.yml:/traefik.yml:ro

  nginx-proxy:
    environment:
      - NGINX_PUBLIC_HOST=localhost
  db:
    ports:
      - 5432:5432
    environment:
      - WITH_SAMPLE_DATA=yes
  backend:
    ports:
      - 5000:5000
    environment:
      - FLASK_CONFIGURATION=development
#  pg-tileserv:
#    ports:
#      - 7800:7800